### ISSUE TITLE
automatic control rod does not work

### ISSUE THREAD

**Issue by Darek505** [Voxelstice/ntm-rbmk-simulator#2]
https://github.com/user-attachments/assets/1b5bd8c8-91f8-481f-8e41-036a53ac153b

title, the rod after installation simply remains at 0% regardless of anything, not only the temperature in the config, but even manually

**Comment by Voxelstice** [comment]
as it turns out, i forgot to update the control rod itself
this site is currently a disaster in terms of the code but i might be able to salvage something out of it at one point

**Comment by Voxelstice** [comment]
*not tested by the way

**Comment by Darek505** [comment]
The error is still there, apparently it's something else?

**Comment by Voxelstice** [comment]
idk it works
![image](https://github.com/user-attachments/assets/35d430c1-d4ae-44bb-9d2c-d30f0180d5ec)
it's showing 1% because i never tested it (i multiplied the target level by 0.01 for some reason)

Honestly this entire simulation just needs to be rewritten entirely, and im honestly just thinking of making it an standalone C++ app, but most of the time im occupied with school so

**Comment by Darek505** [comment]
Strange, from my side it looks something like this:


https://github.com/user-attachments/assets/4d719afd-f541-4519-9f53-097696e5c21d

**Comment by Voxelstice** [comment]
yeah honestly at that point im not even sure
